Consider the below code to answer further questions:

import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)



**Q1.** Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

**Ans:**

There is a difference in the data type of the variables list_ and array_list. The variable list_ is a Python list object, while the variable array_list is a NumPy array object.

In [2]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print("list_ Data type: ", type(list_))
print("array_list Data type: ", type(array_list))

list_ Data type:  <class 'list'>
array_list Data type:  <class 'numpy.ndarray'>


**Q2.** Write a code to print the data type of each and every element of both the variables list_ and arra_list.

**Ans:**

In [6]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print("Data type of items in list_:")
for i in list_:
    print(type(i))
print("\nData type of items in array_list:")
for i in array_list:
    print(type(i))

Data type of items in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of items in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


**Q3.** Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

**Ans:**

array_list = np.array(object = list_, dtype = int)

The dtype parameter is used to specify the data type of the elements in the resulting NumPy array. Here, we are specifying int as the data type, so all the elements in the resulting array_list will be of integer type.

In [18]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_, dtype = int)
print("Data type of items in list_:")
for i in list_:
    print(type(i))
print("\nData type of items in array_list:")
for i in array_list:
    print(type(i))

Data type of items in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of items in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

**Q4.** Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

**Ans:**

In [10]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
print("shape of num_array: ", num_array.shape)
print("size of num_array: ", num_array.size)

shape of num_array:  (2, 3)
size of num_array:  6


**Q5.** Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

**Ans:**

In [13]:
import numpy as np

Zeros = np.zeros((3,3))
print(Zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Q6.** Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

**Ans:**

In [15]:
import numpy as np

I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
